swagger: '2.0'
info:
  version: '1.0'
  title: "ProgettoIS2"
  description: It is an API that allows the user to upload images and videos and to do some processing on them.
  license:
    name: MIT
host: blooming-stream-08914.herokuapp.com
basePath: /
tags:
- name: "Images"
- name: "Videos"
- name: "Images Filters"
- name: "Images Formats"
- name: "Images Transformations"
- name: "Videos Transformations"

schemes:
- http
produces:
- application/json
paths:  
  /images:
    get:
      tags:
        - "Images"
      summary: Return an image
      produces:
        - image/jpeg
        - image/png
      parameters:
        - in: query
          name: id
          required: true
          type: string
          x-example: "5df120c4318a2b00163eb780"
      responses:
        200:
          description: Successful Response - The image is returned
          schema:
            type: file
            format: binary
                
    post:
      tags:
        - "Images"
      summary: Upload a new image
      consumes:
        - multipart/form-data
      produces: 
        - application/json
      parameters:
        - in: formData
          name: file
          required: true
          type: file
          description: The image to upload, jpg or png.
      responses:
        200:
          description: Successful Response - The ID of the uploaded image is returned
          schema:
            $ref: '#/definitions/ImVidResponse'
                
  /videos:
    get:
      tags:
        - "Videos"
      summary: Return a video
      produces:
        - multipart/form-data
      parameters:
        - in: query
          name: id
          required: true
          type: string
      responses:
        200:
          description: Successful Response - The video is returned
          schema:
            type: string
            format: binary
            
    post:
      tags:
        - "Videos"
      summary: Upload a new video
      consumes:
        - multipart/form-data
      produces: 
        - application/json
      parameters:
        - in: formData
          name: file
          required: true
          type: file
          description: The video to upload
      responses:
        200:
          description: Successful Response - The ID of the uploaded video is returned
          schema:
            $ref: '#/definitions/ImVidResponse'
            
  /images-transformations:   
    get:
      tags:
        - "Images Transformations"
      summary: List the available image transformations
      produces:
        - application/json
      responses:
        200:
          description: Successful Response - List all the available transformations
          schema:
            $ref: '#/definitions/TransformationList'

  /image-transformations/rotate:
    post: 
      tags:
        - "Images Transformations"
      summary: Apply the rotation to an Image
      parameters:
        - in: query
          name: source
          type: string
          required: true
          x-example: 5df120c4318a2b00163eb780
        - in: query
          name: angle
          type: integer
          required: true
          x-example: 30
      produces:
        - application/json
      responses:
        201:
          description: Successful Response - The ID of the new rotated image is returned
          schema:
            $ref: '#/definitions/ImVidResponse'

  /image-transformations/resize:
    post: 
      tags:
        - "Images Transformations"
      summary: Returns a resized copy of an image
      parameters:
        - in: query
          name: source
          type: string
          required: true
          x-example: 5df120c4318a2b00163eb780
        - in: query
          name: width
          type: integer
          required: true
        - in: query
          name: height
          type: integer
          required: true
      produces:
        - application/json
      responses:
        201:
          description: Successful Response - The ID of the new resized image is returned
          schema:
            $ref: '#/definitions/ImVidResponse'
  
  /image-transformations/transpose:
    post: 
      tags:
        - "Images Transformations"
      summary: Apply the transpose to an Image
      parameters:
        - in: query
          name: source
          type: string
          required: true
          x-example: 5df120c4318a2b00163eb780
        - in: query
          name: side
          type: string
          required: true
          enum:
            - x
            - y
            - xy
          x-example: x
      produces:
        - application/json
      responses:
        201:
          description: Successful Response - The ID of the new transposed image is returned
          schema:
            $ref: '#/definitions/ImVidResponse'

  /image-transformations/crop:
    post: 
      tags:
        - "Images Transformations"
      summary: Returns a copy of a rectangular region from the current image
      parameters:
        - in: query
          name: source
          type: string
          required: true
          x-example: 5df120c4318a2b00163eb780
        - in: query
          name: left
          type: integer
          required: true
        - in: query
          name: upper
          type: integer
          required: true
        - in: query
          name: right
          type: integer
          required: true
        - in: query
          name: lower
          type: integer
          required: true
      produces:
        - application/json
      responses:
        201:
          description: Successful Response - The ID of the new cropped image is returned
          schema:
            $ref: '#/definitions/ImVidResponse'

  /image-transformations/transform:
    post: 
      tags:
        - "Images Transformations"
      summary: Applies a perspective transform to the image, and places the result in a new image with the given size
      parameters:
        - in: query
          name: source
          type: string
          required: true
          x-example: 5df120c4318a2b00163eb780
        - in: query
          name: width
          type: integer
          required: true
        - in: query
          name: height
          type: integer
          required: true
        - in: query
          name: a
          type: integer
          required: true
        - in: query
          name: b
          type: integer
          required: true
        - in: query
          name: c
          type: integer
          required: true
        - in: query
          name: d
          type: integer
          required: true
        - in: query
          name: e
          type: integer
          required: true
        - in: query
          name: f
          type: integer
          required: true
        - in: query
          name: g
          type: integer
          required: true
        - in: query
          name: h
          type: integer
          required: true
      produces:
        - application/json
      responses:
        201:
          description: Successful Response - The ID of the new transformed image is returned
          schema:
            $ref: '#/definitions/ImVidResponse'

/video-transformation:
    get:
      tags:
        - "Video Transformation"
      summary: List the available video transformation 
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        200:
          description: Successful Response
          schema:
            $ref: '#/definitions/VideoTranformationList'
          
            type: object
            properties:
              available:
                type: array
                items:
                  $ref: '#/definitions/videoTransformationList'
            example:
              avaliable:
                - name: cut
                  parameters: "source:videoID, pixel_x:int, pixel_y:int"
                  description: Resize a video with respect to parameters pixel_x (width) and pixel_y (height)
                - name: speedup
                  parameters: "source:videoID, factor:double"
                  description: Speed up a video at factor time
                - name: "resize",
                  schema: "source:videoID, pixel_x:int, pixel_y:int",
                  description: "Resize a video with respect to parameters pixel_x (width) and pixel_y (height)"

  /video-transformation/speedup:
    post: 
      tags:
        - "Speed Up"
      summary: Speed up a video at factor time
      parameters:
        - in: query
          name: source
          type: string
          required: true
        - in: query
          name: factor
          type: double
          required: true
      consumes:
        - application/json
      produces:
        - application/json
      responses:xx
        201:
          description: Successful Response
          schema:
            $ref: '#/definitions/ImVidResponse'
  /video-transformation/cut:
    post: 
      tags:
        - "Cut"
      summary: Cut a video from start_time to end_time
      parameters:
        - in: query
          name: source
          type: string
          required: true
        - in: query
          name: start_time
          type: double
          required: true
        - in: query
          name: end_time
          type: double
          required: true
      consumes:
        - application/json
      produces:
        - application/json
      responses:xx
        201:
          description: Successful Response
          schema:
            $ref: '#/definitions/ImVidResponse'
  /video-transformation/resize:
    post: 
      tags:
        - "Resize"
      summary: Resize a video with respect to parameters pixel_x (width) and pixel_y (height)
      parameters:
        - in: query
          name: source
          type: string
          required: true
        - in: query
          name: pixel_x
          type: double
          required: true
        - in: query
          name: pixel_y
          type: double
          required: true
      consumes:
        - application/json
      produces:
        - application/json
      responses:xx
        201:
          description: Successful Response
          schema:
            $ref: '#/definitions/ImVidResponse'
  

  /image-filters:
    get:
      tags:
        - "Images Filters"
      summary: List the available image filters
      produces:
        - application/json
      responses:
        200:
          description: Successful Response - List all the available filters
          schema:
            $ref: '#/definitions/FiltersList'

  /image-filters/greyscale:
    post: 
      tags:
        - "Images Filters"
      summary: Apply the greyscale filter to an Image
      parameters:
        - in: query
          name: source
          type: string
          required: true
          x-example: 5df120c4318a2b00163eb780
      produces:
        - application/json
      responses:
        201:
          description: Successful Response - The ID of the new modified image is returned
          schema:
            $ref: '#/definitions/ImVidResponse'
  
  /image-filters/binary:
    post: 
      tags:
        - "Images Filters"
      summary: Apply the binary filter to an image
      parameters:
        - in: query
          name: source
          type: string
          required: true
          x-example: 5df120c4318a2b00163eb780
        - in: query
          name: treshsold
          type: integer
          minimum: 0
          maximum: 255
          required: true
          x-example: 100
      produces:
        - application/json
      responses:
        201:
          description: Successful Response - The ID of the new modified image is returned
          schema:
            $ref: '#/definitions/ImVidResponse'
 
  /image-filters/invert:
    post: 
      tags:
        - "Images Filters"
      summary: Apply the invert filter to an image
      parameters:
        - in: query
          name: source
          type: string
          required: true
          x-example: 5df120c4318a2b00163eb780
      produces:
        - application/json
      responses:
        201:
          description: Successful Response - The ID of the new modified image is returned
          schema:
            $ref: '#/definitions/ImVidResponse' 
            
  /image-formats:
    get:
      tags:
        - "Images Formats"
      summary: List the available image formats
      produces:
        - application/json
      responses:
        200:
          description: Successful Response - List all the available formats
          schema:
            $ref: '#/definitions/FormatsList'
            
  /image-formats/png:
    post:
      tags:
        - "Images Formats"
      summary: Convert the image format to PNG
      parameters:
        - in: query
          name: source
          type: string
          required: true
          x-example: 5df120c4318a2b00163eb780
      produces:
        - application/json
      responses:
        200:
          description: Successful Response - The ID of the new modified image is returned
          schema:
            $ref: '#/definitions/ImVidResponse'
            
  /image-formats/jpeg:
    post:
      tags:
        - "Images Formats"
      summary: Convert the image format to JPEG
      parameters:
        - in: query
          name: source
          type: string
          required: true
          x-example: 5df120c4318a2b00163eb780
      produces:
        - application/json
      responses:
        200:
          description: Successful Response - The ID of the new modified image is returned
          schema:
            $ref: '#/definitions/ImVidResponse'

definitions:
  ImVidUpload:
    title: ImVidUpload
    type: object
    properties:
      file:
        type: string
        format: binary

  ImVidResponse:
    title: Response
    type: object
    properties:
      id:
        type: string
        example: 5df12355318a2b00163eb786

  TransformationList:
    title: TransformationList
    type: object
    properties:
      available:
        type: array
        items:
          $ref: '#/definitions/Transformation'
    example:
      avaliable:
        - name: Rotate
          parameters: "source:imgID angle:int"
          description: Rotate the image by the given angle

  Transformation:
    title: Transformation 
    type: object
    properties:
      name:
        type: string
      parameters:
        type: string
      description:
        type: string
    required:
      - name
      - parameters
      - description
      
  FiltersList:
    title: FiltersList
    type: object
    properties:
      available:
        type: array
        items:
          $ref: '#/definitions/Filter'
    example:
      avaliable:
        - name: greyscale
          parameters: "source:imgID"
          description: Convert an image into greyscale in 8 bits
        - name: binary
          parameters: "source:imgID treshold:int"
          description: >-
            Every pixel of the image is made either white or black
            It dependes on the treshold value
  Filter:
    title: Filter
    type: object
    properties:
      name:
        type: string
      parameters:
        type: string
      description:
        type: string
    required:
      - name
      - parameters
      - description
      
  FormatsList:
    title: FormatsList
    type: object
    properties:
      avaliable:
        type: array
        items:
          $ref: '#/definitions/Format'
    example:
      avaliable:
        - name: png
          parameters: "source:imgID"
          description: Convert the format of the image to png
        - name: jpeg
          parameters: "source:imgID"
          description: Convert the format of the image to jpeg
  Format:
    title: Format
    type: object
    properties:
      name:
        type: string
      parameters:
        type: string
      description:
        type: string
    required:
      - name
      - parameters
      - description


